version: '3.9'

services:
    rabbitmq:
        image: "rabbitmq:3.12.4-management-alpine"
        hostname: rabbitmq
        ports:
        - "15672:15672"
        - "5672:5672"
        volumes:
        - "rabbitmq_data:/var/lib/rabbitmq/mnesia"
        environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

volumes:
  rabbitmq_data: